create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  full_name text not null,
  role_label text not null default 'Biomedical Workspace Member',
  avatar_label text not null default 'BC',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.chats (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  mode text not null default 'general' check (mode in ('general', 'report', 'device', 'troubleshoot')),
  preview text,
  starred boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.chats (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  room text not null check (room in ('discussion', 'expert_qna')),
  user_id uuid not null references auth.users (id) on delete cascade,
  user_name text not null,
  user_role text not null,
  avatar_label text not null,
  content text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists chats_user_id_updated_at_idx on public.chats (user_id, updated_at desc);
create index if not exists messages_chat_id_created_at_idx on public.messages (chat_id, created_at asc);
create index if not exists community_posts_room_created_at_idx on public.community_posts (room, created_at asc);

alter table public.profiles enable row level security;
alter table public.chats enable row level security;
alter table public.messages enable row level security;
alter table public.community_posts enable row level security;

create policy "profiles_select_own"
  on public.profiles
  for select
  using (auth.uid() = id);

create policy "profiles_insert_own"
  on public.profiles
  for insert
  with check (auth.uid() = id);

create policy "profiles_update_own"
  on public.profiles
  for update
  using (auth.uid() = id);

create policy "chats_select_own"
  on public.chats
  for select
  using (auth.uid() = user_id);

create policy "chats_insert_own"
  on public.chats
  for insert
  with check (auth.uid() = user_id);

create policy "chats_update_own"
  on public.chats
  for update
  using (auth.uid() = user_id);

create policy "chats_delete_own"
  on public.chats
  for delete
  using (auth.uid() = user_id);

create policy "messages_select_own"
  on public.messages
  for select
  using (auth.uid() = user_id);

create policy "messages_insert_own"
  on public.messages
  for insert
  with check (auth.uid() = user_id);

create policy "messages_delete_own"
  on public.messages
  for delete
  using (auth.uid() = user_id);

create policy "community_posts_select_public"
  on public.community_posts
  for select
  using (true);

create policy "community_posts_insert_own"
  on public.community_posts
  for insert
  with check (auth.uid() = user_id);
