-- Create community_posts table for production community rooms
CREATE TABLE IF NOT EXISTS public.community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room TEXT NOT NULL CHECK (room IN ('discussion', 'expert_qna')),
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  user_role TEXT NOT NULL,
  avatar_label TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS community_posts_room_created_at_idx
ON public.community_posts (room, created_at ASC);

ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'community_posts'
      AND policyname = 'community_posts_select_public'
  ) THEN
    CREATE POLICY "community_posts_select_public"
      ON public.community_posts
      FOR SELECT
      USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'community_posts'
      AND policyname = 'community_posts_insert_own'
  ) THEN
    CREATE POLICY "community_posts_insert_own"
      ON public.community_posts
      FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;
